In [346]:
import numpy as np
import pandas as pd

Определяем функции

In [347]:
def U(x):
    if x <= 1/2: 
        return 1
    else: 
        return 0


def f(x):
    return x * x

Объявляем переменные и устанавливаем начальное условие

In [459]:
h = .1
tau = .1
x = 0
a = np.zeros((12,12))

for i in range(0, 11):
    q = x + i * h
    a[0][i] = U(q)

Трехточечная явная схема

In [462]:
for i in range(0, 11):
    for j in range(0, 11):
        next_x = x + i * h
        a[i+1][j] = a[i][j] - next_x * tau / h * (a[i][j] - a[i][j-1]) \
        + tau * f(next_x)

Четырехточечная неявная схема. Следует перезапустить блок с переменными для обнуления значений.

In [460]:
for i in range(0, 11):
    for j in range(0, 11):
        next_x = x + i * h
        a[i+1][j] = a[i][j] + next_x * tau / (2 * h) * (a[i+1][j+1] - a[i+1][j-1]) \
        + tau * f(x + (i+1) * h)

Импортируем в датафрейм pandas для управления данными

In [464]:
df = pd.DataFrame(a)
pd.set_option('expand_frame_repr', True)
dfr = df.round(3)
dfr.loc[:10, :10]

,0,1,2,3,4,5,6,7,8,9,10
0,1.000,1.000,1.000,1.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000
1,1.000,1.000,1.000,1.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000
2,0.901,1.001,1.001,1.001,1.001,1.001,0.101,0.001,0.001,0.001,0.001
3,0.724,0.984,1.004,1.004,1.004,1.004,0.285,0.025,0.005,0.005,0.005
4,0.515,0.915,1.007,1.013,1.013,1.013,0.509,0.111,0.019,0.013,0.013
5,0.323,0.769,0.984,1.025,1.027,1.027,0.725,0.284,0.070,0.029,0.027
6,0.184,0.569,0.899,1.027,1.048,1.049,0.898,0.527,0.200,0.072,0.051
7,0.106,0.370,0.733,0.983,1.068,1.081,1.021,0.782,0.428,0.181,0.096
8,0.076,0.230,0.523,0.852,1.052,1.116,1.107,0.994,0.720,0.398,0.200
9,0.073,0.164,0.346,0.647,0.950,1.123,1.172,1.142,0.997,0.713,0.416
10,0.080,0.155,0.255,0.449,0.750,1.040,1.200,1.242,1.201,1.041,0.756